#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Vi-QuickFix
version:      1.116
version_from: lib/Vi/QuickFix.pm
installdirs:  site
requires:
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
